# Generated by Django 4.0.5 on 2022-08-07 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcomment',
            old_name='Comment',
            new_name='comment',
        ),
    ]
